services:
  node-courses-web-backend:
    build: .
    image: darshanaswath/webbackendapp:latest
    environment:
      - PORT=3000

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
