services:
  node-courses-web-backend:
    build: .
    image: darshanaswath/webbackendapp:latest
    environment:
      - PORT=3000
      - OPEN_API_TOKEN=$${{ secrets.OPEN_API_TOKEN }}
      - ANTHROPIC_API_KEY=$${{ secrets.ANTHROPIC_API_KEY }}
      - JWT_SECRET=$${{ secrets.JWT_SECRET }}
      - MONGO_USERNAME=$${{ secrets.MONGO_USERNAME }}
      - MONGO_PASSWORD=$${{ secrets.MONGO_PASSWORD }}
      - CLIENT_URL=$${{ secrets.CLIENT_URL }}

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-courses-web-backend
