services:
  nginx:
    ports:
      - "80:80"

  node-courses-web-backend:
    image: darshanaswath/webbackendapp:prod
    deploy:
      replicas: 5
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm run build
