services:
  nginx:
    ports:
      - "80:80"

  node-courses-web-backend:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm run build
