name: deploypipeline
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: deploy
      - name: setup docker buildx
        uses: docker/setup-buildx-action@master
      - name: docker login
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          push: true
          tags: darshanaswath/webbackendapp:latest
