name: deploypipeline
on:
  push:
    branches:
      - "main"
jobs:
  deploy-to-droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: SSH into Droplet, clone repo, and build using Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            mkdir -p ~/webbackendapp

            cd ~/webbackendapp

            rm .env

            cat <<EOF >> .env
            OPEN_API_TOKEN=${{ secrets.OPEN_API_TOKEN }}
            ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
            JWT_SECRET='${{ secrets.JWT_SECRET }}'
            MONGO_DB_URI='${{ secrets.MONGO_DB_URI }}'
            EOF

            if [ ! -d ".git" ]; then
              git clone https://github.com/darshan-aswathappa/cousre-recommendation-system-backend.git .
            else
              git reset --hard
              git pull origin main
            fi

            docker compose down -v

            docker swarm init --advertise-addr 64.225.28.58

            docker stack deploy -c docker-compose.yml -c docker-compose.prod.yml neucrapp

            docker stack ls 

            docker node ls

            docker stack services neucrapp
